version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: makeziper_db
    shm_size: 1gb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    command: >
      postgres
      -c shared_buffers=256MB
      -c work_mem=64MB
      -c maintenance_work_mem=128MB
      -c max_connections=50
      -c effective_cache_size=768MB
    volumes:
      - back_makeziper_pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 2s
      timeout: 3s
      retries: 5
    networks:
      - makeziper_net

  python_doc: # ← НОВЫЙ СЕРВИС
    build:
      context: ./internal/doc/python # ← папка где Dockerfile Python
    container_name: makeziper_doc_service
    networks:
      - makeziper_net
    expose:
      - "8000"
    restart: unless-stopped

  app:
    build: .
    container_name: makeziper_app
    env_file:
      - .env
    environment:
      DOC_SERVICE_URL: "http://python_doc:8000/convert" # ← НОВОЕ!
    depends_on:
      db:
        condition: service_healthy
      python_doc:
        condition: service_started
    ports:
      - "${PORT:-8080}:8080"
    restart: unless-stopped
    networks:
      - makeziper_net

networks:
  makeziper_net:

volumes:
  back_makeziper_pgdata:
